language: objective-c

osx_image: xcode8

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild clean build -workspace cert-wallet.xcworkspace -scheme cert-wallet -sdk iphonesimulator -destination "OS=10.0,name=iPhone 6" | xcpretty -c || true
- xcodebuild test -workspace cert-wallet.xcworkspace -scheme cert-wallet -sdk iphonesimulator -destination "OS=10.0,name=iPhone 6" | xcpretty -c
