language: objective-c
osx_image: xcode9
install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild clean build -workspace cert-wallet.xcworkspace -scheme cert-wallet -sdk iphonesimulator -destination "OS=11.0,name=iPhone SE" CODE_SIGNING_REQUIRED=NO | xcpretty -c || true
  - xcodebuild test        -workspace cert-wallet.xcworkspace -scheme cert-wallet -sdk iphonesimulator -destination "OS=11.0,name=iPhone SE" CODE_SIGNING_REQUIRED=NO | xcpretty -c
